//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Data.RopSql.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageRepository {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageRepository() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Data.RopSql.Resources.MessageRepository", typeof(MessageRepository).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um dos atributos informados para exibição não foram definidos como listáveis..
        /// </summary>
        public static string RopSql_AttributeNotListable_BR {
            get {
                return ResourceManager.GetString("RopSql_AttributeNotListable_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eines der attribute display informiert nicht börsenfähig definiert..
        /// </summary>
        public static string RopSql_AttributeNotListable_DE {
            get {
                return ResourceManager.GetString("RopSql_AttributeNotListable_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uno de los atributos para mostrar no informó define como listaveis..
        /// </summary>
        public static string RopSql_AttributeNotListable_ES {
            get {
                return ResourceManager.GetString("RopSql_AttributeNotListable_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;un des attributs à afficher informé pas défini comme listables..
        /// </summary>
        public static string RopSql_AttributeNotListable_FR {
            get {
                return ResourceManager.GetString("RopSql_AttributeNotListable_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the attributes to display informed not defined as listable..
        /// </summary>
        public static string RopSql_AttributeNotListable_US {
            get {
                return ResourceManager.GetString("RopSql_AttributeNotListable_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A conexão ao banco de dados encontra-se fechada, é necessário conectar..
        /// </summary>
        public static string RopSql_ClosedDatabaseConnection_BR {
            get {
                return ResourceManager.GetString("RopSql_ClosedDatabaseConnection_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Verbindung zur Datenbank geschlossen wird, müssen Sie die Verbindung..
        /// </summary>
        public static string RopSql_ClosedDatabaseConnection_DE {
            get {
                return ResourceManager.GetString("RopSql_ClosedDatabaseConnection_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La conexión a la base de datos está cerrada, debe conectar..
        /// </summary>
        public static string RopSql_ClosedDatabaseConnection_ES {
            get {
                return ResourceManager.GetString("RopSql_ClosedDatabaseConnection_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La connexion à la base de données est fermée, vous devez vous connecter..
        /// </summary>
        public static string RopSql_ClosedDatabaseConnection_FR {
            get {
                return ResourceManager.GetString("RopSql_ClosedDatabaseConnection_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection to the database is closed, you must connect..
        /// </summary>
        public static string RopSql_ClosedDatabaseConnection_US {
            get {
                return ResourceManager.GetString("RopSql_ClosedDatabaseConnection_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuração para conexão ao banco de dados não encontrada..
        /// </summary>
        public static string RopSql_ConnectionConfigurationNotFound_BR {
            get {
                return ResourceManager.GetString("RopSql_ConnectionConfigurationNotFound_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellen zur Verbindung mit der Datenbank nicht gefunden..
        /// </summary>
        public static string RopSql_ConnectionConfigurationNotFound_DE {
            get {
                return ResourceManager.GetString("RopSql_ConnectionConfigurationNotFound_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración para la conexión a la base de datos no se ha encontrado..
        /// </summary>
        public static string RopSql_ConnectionConfigurationNotFound_ES {
            get {
                return ResourceManager.GetString("RopSql_ConnectionConfigurationNotFound_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration pour la connexion à la base de données introuvable..
        /// </summary>
        public static string RopSql_ConnectionConfigurationNotFound_FR {
            get {
                return ResourceManager.GetString("RopSql_ConnectionConfigurationNotFound_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting to the database connection not found..
        /// </summary>
        public static string RopSql_ConnectionConfigurationNotFound_US {
            get {
                return ResourceManager.GetString("RopSql_ConnectionConfigurationNotFound_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caminho do repositório de dados não encontrado..
        /// </summary>
        public static string RopSql_DataSourceNotFound_BR {
            get {
                return ResourceManager.GetString("RopSql_DataSourceNotFound_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daten-Repository nicht gefunden..
        /// </summary>
        public static string RopSql_DataSourceNotFound_DE {
            get {
                return ResourceManager.GetString("RopSql_DataSourceNotFound_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ruta de datos repositorio no se encuentra..
        /// </summary>
        public static string RopSql_DataSourceNotFound_ES {
            get {
                return ResourceManager.GetString("RopSql_DataSourceNotFound_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemin du référentiel de données introuvable..
        /// </summary>
        public static string RopSql_DataSourceNotFound_FR {
            get {
                return ResourceManager.GetString("RopSql_DataSourceNotFound_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data repository path not found..
        /// </summary>
        public static string RopSql_DataSourceNotFound_US {
            get {
                return ResourceManager.GetString("RopSql_DataSourceNotFound_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um ou mais dos campos obrigatórios não foram preenchidos ou são inválidos..
        /// </summary>
        public static string RopSql_InvalidAttribute_BR {
            get {
                return ResourceManager.GetString("RopSql_InvalidAttribute_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einer oder mehrere der erforderlichen Felder wurden nicht ausgefüllt oder ungültig sind..
        /// </summary>
        public static string RopSql_InvalidAttribute_DE {
            get {
                return ResourceManager.GetString("RopSql_InvalidAttribute_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uno o más de los campos requeridos no fueron llenados o no son válidos..
        /// </summary>
        public static string RopSql_InvalidAttribute_ES {
            get {
                return ResourceManager.GetString("RopSql_InvalidAttribute_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un ou plusieurs des champs obligatoires n&apos;ont pas été remplis ou ne sont pas valides..
        /// </summary>
        public static string RopSql_InvalidAttribute_FR {
            get {
                return ResourceManager.GetString("RopSql_InvalidAttribute_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of mandatory fields not were filled or are invalid..
        /// </summary>
        public static string RopSql_InvalidAttribute_US {
            get {
                return ResourceManager.GetString("RopSql_InvalidAttribute_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As credenciais informadas para conexão ao banco de dados são inválidas..
        /// </summary>
        public static string RopSql_InvalidConnectionCredentials_BR {
            get {
                return ResourceManager.GetString("RopSql_InvalidConnectionCredentials_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informierte Anmeldeinformationen für die Verbindung mit der Datenbank sind ungültig..
        /// </summary>
        public static string RopSql_InvalidConnectionCredentials_DE {
            get {
                return ResourceManager.GetString("RopSql_InvalidConnectionCredentials_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informados credenciales para conectarse a la base de datos no son válidos..
        /// </summary>
        public static string RopSql_InvalidConnectionCredentials_ES {
            get {
                return ResourceManager.GetString("RopSql_InvalidConnectionCredentials_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pouvoirs éclairées pour la connexion à la base de données ne sont pas valides..
        /// </summary>
        public static string RopSql_InvalidConnectionCredentials_FR {
            get {
                return ResourceManager.GetString("RopSql_InvalidConnectionCredentials_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informed credentials for connecting to the database are invalid..
        /// </summary>
        public static string RopSql_InvalidConnectionCredentials_US {
            get {
                return ResourceManager.GetString("RopSql_InvalidConnectionCredentials_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ação de persistência inválida..
        /// </summary>
        public static string RopSql_InvalidPersistenceAction_BR {
            get {
                return ResourceManager.GetString("RopSql_InvalidPersistenceAction_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistenz aktion ungültig..
        /// </summary>
        public static string RopSql_InvalidPersistenceAction_DE {
            get {
                return ResourceManager.GetString("RopSql_InvalidPersistenceAction_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acción de persistencia no válido..
        /// </summary>
        public static string RopSql_InvalidPersistenceAction_ES {
            get {
                return ResourceManager.GetString("RopSql_InvalidPersistenceAction_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistance action invalide..
        /// </summary>
        public static string RopSql_InvalidPersistenceAction_FR {
            get {
                return ResourceManager.GetString("RopSql_InvalidPersistenceAction_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid persistence action..
        /// </summary>
        public static string RopSql_InvalidPersistenceAction_US {
            get {
                return ResourceManager.GetString("RopSql_InvalidPersistenceAction_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum registro foi encontrado com o critério de pesquisa informado..
        /// </summary>
        public static string RopSql_RecordNotFound_BR {
            get {
                return ResourceManager.GetString("RopSql_RecordNotFound_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Datensätze gefunden wurden für die Suchkriterien eingegeben..
        /// </summary>
        public static string RopSql_RecordNotFound_DE {
            get {
                return ResourceManager.GetString("RopSql_RecordNotFound_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron registros para los criterios de búsqueda introducidos..
        /// </summary>
        public static string RopSql_RecordNotFound_ES {
            get {
                return ResourceManager.GetString("RopSql_RecordNotFound_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun enregistrement n&apos;a été trouvé pour les critères de recherche saisis..
        /// </summary>
        public static string RopSql_RecordNotFound_FR {
            get {
                return ResourceManager.GetString("RopSql_RecordNotFound_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records were found for the search criteria entered..
        /// </summary>
        public static string RopSql_RecordNotFound_US {
            get {
                return ResourceManager.GetString("RopSql_RecordNotFound_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrução SQL não informada..
        /// </summary>
        public static string RopSql_SQLInstructionNotFound_BR {
            get {
                return ResourceManager.GetString("RopSql_SQLInstructionNotFound_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown SQL-Anweisung..
        /// </summary>
        public static string RopSql_SQLInstructionNotFound_DE {
            get {
                return ResourceManager.GetString("RopSql_SQLInstructionNotFound_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desconocido sentencia SQL..
        /// </summary>
        public static string RopSql_SQLInstructionNotFound_ES {
            get {
                return ResourceManager.GetString("RopSql_SQLInstructionNotFound_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown instruction SQL..
        /// </summary>
        public static string RopSql_SQLInstructionNotFound_FR {
            get {
                return ResourceManager.GetString("RopSql_SQLInstructionNotFound_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown SQL statement..
        /// </summary>
        public static string RopSql_SQLInstructionNotFound_US {
            get {
                return ResourceManager.GetString("RopSql_SQLInstructionNotFound_US", resourceCulture);
            }
        }
    }
}
