//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Data.RopSql.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SQLANSIRepository {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLANSIRepository() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Data.RopSql.Resources.SQLANSIRepository", typeof(SQLANSIRepository).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AS {0} .
        /// </summary>
        public static string DataPersistence_Action_ColumnName {
            get {
                return ResourceManager.GetString("DataPersistence_Action_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO {0} ({1}) VALUES ({2}) .
        /// </summary>
        public static string DataPersistence_Action_Create {
            get {
                return ResourceManager.GetString("DataPersistence_Action_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM {0} WHERE {1}.
        /// </summary>
        public static string DataPersistence_Action_Delete {
            get {
                return ResourceManager.GetString("DataPersistence_Action_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE {0} SET {1} WHERE {2}.
        /// </summary>
        public static string DataPersistence_Action_Edit {
            get {
                return ResourceManager.GetString("DataPersistence_Action_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXEC {0}.
        /// </summary>
        public static string DataPersistence_Action_ExecuteProcedure {
            get {
                return ResourceManager.GetString("DataPersistence_Action_ExecuteProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALL {0}.
        /// </summary>
        public static string DataPersistence_Action_ExecuteProcedure_MySQL {
            get {
                return ResourceManager.GetString("DataPersistence_Action_ExecuteProcedure_MySQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT @@IDENTITY .
        /// </summary>
        public static string DataPersistence_Action_GetLastId {
            get {
                return ResourceManager.GetString("DataPersistence_Action_GetLastId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROUP BY {0}.
        /// </summary>
        public static string DataPersistence_Action_Group {
            get {
                return ResourceManager.GetString("DataPersistence_Action_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOP {0}.
        /// </summary>
        public static string DataPersistence_Action_LimitResult {
            get {
                return ResourceManager.GetString("DataPersistence_Action_LimitResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIMIT {0}.
        /// </summary>
        public static string DataPersistence_Action_LimitResult_MySQL {
            get {
                return ResourceManager.GetString("DataPersistence_Action_LimitResult_MySQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN ({0}).
        /// </summary>
        public static string DataPersistence_Action_MultipleFilter {
            get {
                return ResourceManager.GetString("DataPersistence_Action_MultipleFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER BY {0} {1}.
        /// </summary>
        public static string DataPersistence_Action_OrderResult {
            get {
                return ResourceManager.GetString("DataPersistence_Action_OrderResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT {0} FROM {1} {2} WHERE {3} {4} {5} {6}.
        /// </summary>
        public static string DataPersistence_Action_Query {
            get {
                return ResourceManager.GetString("DataPersistence_Action_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BETWEEN {0} AND {1}.
        /// </summary>
        public static string DataPersistence_Action_RangeFilter {
            get {
                return ResourceManager.GetString("DataPersistence_Action_RangeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INNER JOIN {0} ON {1} = {2}.
        /// </summary>
        public static string DataPersistence_Action_RelationateMandatorily {
            get {
                return ResourceManager.GetString("DataPersistence_Action_RelationateMandatorily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  LEFT JOIN {0} ON {1} = {2} .
        /// </summary>
        public static string DataPersistence_Action_RelationateOptionally {
            get {
                return ResourceManager.GetString("DataPersistence_Action_RelationateOptionally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT.
        /// </summary>
        public static string DataPersistence_ReservedWord_INSERT {
            get {
                return ResourceManager.GetString("DataPersistence_ReservedWord_INSERT", resourceCulture);
            }
        }
    }
}
